services:
  url-shortener-api-postgresql:
    container_name: url-shortener-api-postgresql
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - url-shortener-api-network
    volumes:
      - url_shortener_api_pg_data:/var/lib/postgresql/data

  url-shortener-api-redis:
    container_name: url-shortener-api-redis
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - url-shortener-api-network
    volumes:
      - url_shortener_api_redis_data:/data

  url-shortener-api-cassandra:
    container_name: url-shortener-api-cassandra
    image: cassandra:5.0
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_DC: ${CASSANDRA_DC}
      CASSANDRA_RACK: ${CASSANDRA_RACK}
      CASSANDRA_ENDPOINT_SNITCH: ${CASSANDRA_ENDPOINT_SNITCH}
      CASSANDRA_NUM_TOKENS: ${CASSANDRA_NUM_TOKENS}
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - url-shortener-api-network
    volumes:
      - url_shortener_api_cassandra_data:/var/lib/cassandra

networks:
  url-shortener-api-network:
    driver: bridge

volumes:
  url_shortener_api_pg_data:
  url_shortener_api_redis_data:
  url_shortener_api_cassandra_data:
