apiVersion: apps/v1
kind: Deployment

metadata: 
  name: url-shortener-api
  namespace: url-shortener

spec:
  replicas: 2
  selector:
    matchLabels:
      api: url-shortener-api
  template:
    metadata:
      labels:
        api: url-shortener-api
    spec:
      containers:
        - name: url-shortener-api
          image: vinciusaf/url-shortener-api:a8dd4f1
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi