apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  namespace: url-shortener
type: Opaque
data:
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  PORT: MzMzMw==
  CLIENT_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
  BETTER_AUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMzMz
  DATABASE_URL: cG9zdGdyZXNxbDovL2xvY2FsaG9zdDo1NDMyL3VybF9zaG9ydGVuZXI=
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_NAME: dXJsX3Nob3J0ZW5lcl9wZw==
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
  REDIS_PASSWORD: cmVkaXM=